// Dutch flashcard data.
//
// HOW TO ADD A NEW LESSON:
// Just copy the block below (from "{" to "},") and paste it as a new
// entry in the LESSONS array. Give it the next id/title, then fill in
// "words" as { nl: "...", en: "..." } pairs. That's it — the app picks
// up new lessons automatically, no other code changes needed.
//
// "icon" is optional — a single emoji shown on the card. Only add one
// when it clearly represents the word; leave it out for abstract words,
// grammar terms, pronouns, etc.

const LESSONS = [
  {
    id: 1,
    title: "Lesson 1 — Introductie & De kennismaking",
    words: [
      // People & everyday things
      { nl: "de, het", en: "the" },
      { nl: "een", en: "a" },
      { nl: "de man", en: "the man", icon: "👨" },
      { nl: "de vrouw", en: "the woman", icon: "👩" },
      { nl: "de baby", en: "the baby", icon: "👶" },
      { nl: "de hond", en: "the dog", icon: "🐕" },
      { nl: "de kat", en: "the cat", icon: "🐈" },
      { nl: "het dier", en: "the animal", icon: "🐾" },
      { nl: "de student", en: "the student", icon: "🧑‍🎓" },
      { nl: "de docent", en: "the teacher", icon: "🧑‍🏫" },
      { nl: "de les", en: "the lesson" },
      { nl: "de pen", en: "the pen", icon: "🖊️" },
      { nl: "de tekst", en: "the text" },
      { nl: "het theater", en: "the theatre", icon: "🎭" },
      { nl: "het meisje", en: "the girl", icon: "👧" },
      { nl: "het kind", en: "the child", icon: "🧒" },
      { nl: "het konijn", en: "the rabbit", icon: "🐰" },
      { nl: "het boek", en: "the book", icon: "📖" },
      { nl: "het land", en: "the country", icon: "🌍" },
      { nl: "het adres", en: "the address" },
      { nl: "het antwoord", en: "the answer" },
      { nl: "het huis", en: "the house", icon: "🏠" },
      { nl: "de tablet", en: "the tablet" },
      { nl: "de smartphone", en: "the smartphone", icon: "📱" },
      { nl: "het tennis", en: "the tennis", icon: "🎾" },
      { nl: "Veel succes!", en: "Good luck!" },

      // Names, cities, countries & languages
      { nl: "de naam", en: "the name" },
      { nl: "de voornaam", en: "the first name" },
      { nl: "de achternaam", en: "the surname" },
      { nl: "de stad", en: "the city", icon: "🏙️" },
      { nl: "de taal", en: "the language" },
      { nl: "Nederland", en: "the Netherlands", icon: "🇳🇱" },
      { nl: "het Nederlands", en: "the Dutch language", icon: "🇳🇱" },
      { nl: "Duitsland", en: "Germany", icon: "🇩🇪" },
      { nl: "het Duits", en: "the German language", icon: "🇩🇪" },
      { nl: "Amerika", en: "America", icon: "🇺🇸" },
      { nl: "het Engels", en: "the English language", icon: "🇬🇧" },
      { nl: "China", en: "China", icon: "🇨🇳" },
      { nl: "het Chinees", en: "the Chinese language", icon: "🇨🇳" },
      { nl: "Rusland", en: "Russia", icon: "🇷🇺" },
      { nl: "het Russisch", en: "the Russian language", icon: "🇷🇺" },
      { nl: "Frankrijk", en: "France", icon: "🇫🇷" },
      { nl: "het Frans", en: "the French language", icon: "🇫🇷" },
      { nl: "Spanje", en: "Spain", icon: "🇪🇸" },
      { nl: "Spaans", en: "Spanish", icon: "🇪🇸" },

      // Pronouns
      { nl: "ik", en: "I" },
      { nl: "jij / je", en: "you (informal)" },
      { nl: "u", en: "you (polite)" },
      { nl: "hij", en: "he" },
      { nl: "zij / ze", en: "she" },
      { nl: "wij / we", en: "we" },
      { nl: "jullie", en: "you (plural)" },

      // Time: days, months, seasons
      { nl: "de dag", en: "the day", icon: "📅" },
      { nl: "de week", en: "the week", icon: "🗓️" },
      { nl: "de maand", en: "the month", icon: "📆" },
      { nl: "het jaar", en: "the year", icon: "📆" },
      { nl: "maandag", en: "Monday" },
      { nl: "dinsdag", en: "Tuesday" },
      { nl: "woensdag", en: "Wednesday" },
      { nl: "donderdag", en: "Thursday" },
      { nl: "vrijdag", en: "Friday" },
      { nl: "zaterdag", en: "Saturday" },
      { nl: "zondag", en: "Sunday" },
      { nl: "januari", en: "January" },
      { nl: "februari", en: "February" },
      { nl: "maart", en: "March" },
      { nl: "april", en: "April" },
      { nl: "mei", en: "May" },
      { nl: "juni", en: "June" },
      { nl: "juli", en: "July" },
      { nl: "augustus", en: "August" },
      { nl: "september", en: "September" },
      { nl: "oktober", en: "October" },
      { nl: "november", en: "November" },
      { nl: "december", en: "December", icon: "🎄" },
      { nl: "het seizoen", en: "the season" },
      { nl: "de lente", en: "the spring", icon: "🌸" },
      { nl: "de zomer", en: "the summer", icon: "☀️" },
      { nl: "de herfst", en: "the autumn", icon: "🍂" },
      { nl: "de winter", en: "the winter", icon: "❄️" },

      // Verbs
      { nl: "het werkwoord", en: "the verb" },
      { nl: "kijken", en: "to watch", icon: "👀" },
      { nl: "de televisie", en: "the television", icon: "📺" },
      { nl: "werken", en: "to work" },
      { nl: "op", en: "at / on" },
      { nl: "de universiteit", en: "the university", icon: "🎓" },
      { nl: "antwoorden", en: "to answer" },
      { nl: "de vraag", en: "the question", icon: "❓" },
      { nl: "lopen", en: "to walk", icon: "🚶" },
      { nl: "leren", en: "to learn", icon: "📚" },
      { nl: "vertellen", en: "to tell" },
      { nl: "wonen", en: "to live" },
      { nl: "in", en: "in" },
      { nl: "spreken", en: "to speak", icon: "🗣️" },
      { nl: "al", en: "already" },
      { nl: "lezen", en: "to read", icon: "📖" },
      { nl: "de krant", en: "the newspaper", icon: "📰" },
      { nl: "geven", en: "to give", icon: "🤲" },
      { nl: "zitten", en: "to sit", icon: "🪑" },
      { nl: "buiten", en: "outside" },
      { nl: "hebben", en: "to have" },
      { nl: "zijn", en: "to be" },
      { nl: "sinds", en: "since" },
      { nl: "vanavond", en: "tonight", icon: "🌙" },
      { nl: "komen", en: "to come" },
      { nl: "uit", en: "from / out of" },
      { nl: "binnen", en: "inside" },
      { nl: "nu", en: "now", icon: "⏰" },
      { nl: "op dit moment", en: "at this moment" },

      // Greetings & meeting someone
      { nl: "ontmoeten", en: "to meet", icon: "🤝" },
      { nl: "hoi", en: "hi", icon: "👋" },
      { nl: "wie", en: "who" },
      { nl: "aangenaam", en: "nice to meet you" },
      { nl: "Hoe heet jij?", en: "What is your name?" },
      { nl: "Ik heet...", en: "My name is..." },
      { nl: "en", en: "and" },
      { nl: "waar", en: "where" },
      { nl: "waar vandaan", en: "where from" },
      { nl: "een beetje", en: "a bit" },
      { nl: "wauw", en: "wow", icon: "😲" },
      { nl: "veel", en: "much / many" },

      // Small talk phrases
      { nl: "welke", en: "which" },
      { nl: "Wat leuk!", en: "How nice!", icon: "😄" },
      { nl: "ook", en: "too" },
      { nl: "doen", en: "to do" },
      { nl: "dat", en: "that" },
      { nl: "begrijpen", en: "to understand", icon: "💡" },
      { nl: "mijn", en: "my" },
      { nl: "het beroep", en: "the profession" },
      { nl: "ja", en: "yes", icon: "✅" },
      { nl: "de actrice", en: "the actress", icon: "🎭" },
      { nl: "Wat interessant!", en: "How interesting!" },
      { nl: "beginnen", en: "to begin" },
      { nl: "met", en: "with" },
      { nl: "dankjewel", en: "thank you", icon: "🙏" },
      { nl: "de koffie", en: "the coffee", icon: "☕" },
      { nl: "alsjeblieft", en: "here you are / please" },
      { nl: "goed", en: "right / good", icon: "👍" },
      { nl: "fout", en: "wrong / false", icon: "❌" },

      // A story: guided tour
      { nl: "het verhaal", en: "the story" },
      { nl: "de rondleiding", en: "the guided tour" },
      { nl: "het werk", en: "the job" },
      { nl: "vandaag", en: "today" },
      { nl: "van", en: "from" },
      { nl: "het station", en: "the station", icon: "🚉" },
      { nl: "naar", en: "to" },
      { nl: "zeggen", en: "to say" },
      { nl: "dit", en: "this" },
      { nl: "het paleis", en: "the palace", icon: "🏰" },
      { nl: "vragen", en: "to ask" },
      { nl: "de koning", en: "the king", icon: "👑" },
      { nl: "nee", en: "no", icon: "🚫" },
      { nl: "bij", en: "at" },
      { nl: "de vrijgezel", en: "the bachelor" },
      { nl: "maar", en: "but / only" },
      { nl: "geen", en: "no / none" },
      { nl: "verder", en: "further" },
      { nl: "leuk", en: "fun" },
      { nl: "over", en: "about" },
    ],
  },

  {
    id: 2,
    title: "Lesson 2 — Hoofdstuk 2: Vragen",
    words: [
      // Money & time
      { nl: "laat", en: "late" },
      { nl: "hoeveel", en: "how many / how much" },
      { nl: "het geld", en: "the money", icon: "💰" },

      // Degree words & adjectives
      { nl: "spelen", en: "to play" },
      { nl: "heel", en: "1. very 2. whole" },
      { nl: "zeer", en: "very" },
      { nl: "klein", en: "small" },
      { nl: "nogal", en: "quite" },
      { nl: "boos", en: "angry", icon: "😠" },
      { nl: "redelijk", en: "rather" },
      { nl: "knap", en: "handsome" },
      { nl: "hartstikke", en: "extremely" },
      { nl: "mooi", en: "beautiful" },
      { nl: "gisteren", en: "yesterday" },
      { nl: "morgen", en: "tomorrow" },
      { nl: "nieuw", en: "new", icon: "✨" },
      { nl: "het woord", en: "the word" },
      { nl: "de film", en: "the movie", icon: "🎬" },

      // Time, place & grammar
      { nl: "zo", en: "soon" },
      { nl: "straks", en: "in a little while" },
      { nl: "binnenkort", en: "soon" },
      { nl: "Sinterklaas", en: "Dutch Santa Claus", icon: "🎅" },
      { nl: "daar", en: "there" },
      { nl: "hier", en: "here" },
      { nl: "liggen", en: "to lie (be located)" },
      { nl: "inversie", en: "inversion (grammar)" },
      { nl: "de tuin", en: "the garden", icon: "🌳" },
      { nl: "de kapper", en: "the hairdresser", icon: "💇" },
      { nl: "drinken", en: "to drink", icon: "🥤" },
      { nl: "de stamppot", en: "the hotchpotch", icon: "🍲" },
      { nl: "moeten", en: "to have to, must" },
      { nl: "klaar", en: "ready" },
      { nl: "het vraagwoord", en: "the question word" },

      // Market, questions & everyday life
      { nl: "de markt", en: "the market", icon: "🛒" },
      { nl: "de kinderen", en: "the children", icon: "🧒" },
      { nl: "het bezoek", en: "1. visit 2. guests" },
      { nl: "vaak", en: "often" },
      { nl: "fietsen", en: "to cycle", icon: "🚲" },
      { nl: "lesgeven", en: "to teach", icon: "🧑‍🏫" },
      { nl: "wat", en: "what" },
      { nl: "je adres", en: "your address" },
      { nl: "aan", en: "to" },
      { nl: "welk, welke", en: "which" },
      { nl: "gebruiken", en: "to use" },
      { nl: "wanneer", en: "when" },
      { nl: "de jongen", en: "the boy", icon: "👦" },
      { nl: "de oefening", en: "the exercise" },
      { nl: "jarig zijn", en: "to have a birthday", icon: "🎂" },
      { nl: "plat", en: "flat" },
      { nl: "hoe heten", en: "how ... called (e.g. Hoe heet jij? = What are you called?)" },

      // A phone call
      { nl: "bellen", en: "to call", icon: "📞" },
      { nl: "hallo", en: "hello", icon: "👋" },
      { nl: "Hoe gaat het met jou?", en: "How are you?" },
      { nl: "jou", en: "you" },
      { nl: "de roman", en: "the novel", icon: "📕" },
      { nl: "waarom", en: "why" },
      { nl: "gewoon", en: "normal / just" },
      { nl: "weten", en: "to know" },
      { nl: "nog", en: "still / yet" },
      { nl: "niet", en: "not" },
      { nl: "eten", en: "to eat", icon: "🍽️" },
      { nl: "het idee", en: "the idea" },
      { nl: "mij", en: "me" },
      { nl: "Goed idee!", en: "Good idea!" },
      { nl: "koken", en: "to cook", icon: "🍳" },
      { nl: "thuis", en: "at home", icon: "🏠" },
      { nl: "willen", en: "to want" },
      { nl: "Weet je wat?", en: "You know what?" },
      { nl: "samen", en: "together" },
      { nl: "daarna", en: "then / after that" },
      { nl: "tot", en: "until" },
      { nl: "nemen", en: "to take" },
      { nl: "de trein", en: "the train", icon: "🚆" },
      { nl: "meteen", en: "immediately" },
      { nl: "prima", en: "fine" },
      { nl: "de buurt", en: "the neighbourhood" },
      { nl: "de kilometer", en: "the kilometre" },
      { nl: "het Centraal Station", en: "the Central Station", icon: "🚉" },
      { nl: "ongeveer", en: "approximately" },
      { nl: "dan", en: "then" },
      { nl: "zien", en: "to see", icon: "👀" },
      { nl: "Tot straks!", en: "See you later!", icon: "👋" },
      { nl: "doei", en: "bye", icon: "👋" },

      // Wrapping up
      { nl: "door", en: "through" },
      { nl: "kennen", en: "to know" },
      { nl: "zuchten", en: "to sigh" },
      { nl: "kunnen", en: "1. to be able to 2. to be available" },
      { nl: "druk", en: "1. busy 2. crowded" },
      { nl: "de eeuw", en: "the century" },
      { nl: "het einde", en: "the end", icon: "🏁" },
    ],
  },

  {
    id: 3,
    title: "Lesson 3 — Hoofdstuk 3: Boodschappen doen",
    words: [
      // Adjectives & opposites
      { nl: "lelijk", en: "ugly" },
      { nl: "slecht", en: "bad" },
      { nl: "lang", en: "1. long 2. tall (of people)" },
      { nl: "kort", en: "short" },
      { nl: "de tekst", en: "the text" },
      { nl: "de zin", en: "the sentence" },
      { nl: "zacht", en: "1. soft 2. slow" },
      { nl: "hard", en: "1. hard 2. loud 3. fast" },
      { nl: "de stem", en: "the voice", icon: "🗣️" },
      { nl: "het kussen", en: "the pillow", icon: "🛏️" },
      { nl: "de appel", en: "the apple", icon: "🍎" },
      { nl: "luisteren", en: "to listen", icon: "👂" },
      { nl: "rijk", en: "rich", icon: "💰" },
      { nl: "arm", en: "poor" },
      { nl: "honger hebben", en: "to be hungry", icon: "🍽️" },
      { nl: "interessant", en: "interesting" },
      { nl: "saai", en: "boring", icon: "😴" },
      { nl: "licht", en: "light", icon: "💡" },
      { nl: "donker", en: "dark", icon: "🌑" },
      { nl: "het gezicht", en: "the face", icon: "😊" },
      { nl: "koud", en: "cold", icon: "🥶" },
      { nl: "rijden", en: "to drive", icon: "🚗" },
      { nl: "oud", en: "old", icon: "👴" },
      { nl: "staan", en: "to stand", icon: "🧍" },
      { nl: "de bakker", en: "the baker", icon: "🥖" },
      { nl: "bakken", en: "to bake", icon: "🍞" },
      { nl: "warm", en: "warm", icon: "🔥" },
      { nl: "het brood", en: "1. the bread 2. the loaf of bread", icon: "🍞" },
      { nl: "het ei", en: "the egg", icon: "🥚" },
      { nl: "gezellig", en: "cosy, sociable", icon: "😊" },
      { nl: "ongezellig", en: "not cosy, cheerless" },
      { nl: "niemand", en: "nobody" },
      { nl: "het feest", en: "the party", icon: "🎉" },
      { nl: "dik", en: "fat" },
      { nl: "dun", en: "thin" },
      { nl: "de hamburger", en: "the hamburger", icon: "🍔" },
      { nl: "de wortel", en: "the carrot", icon: "🥕" },

      // More adjectives & things around the house
      { nl: "stom", en: "stupid" },
      { nl: "krijgen", en: "to get" },
      { nl: "de straf", en: "the punishment" },
      { nl: "rustig", en: "quiet", icon: "🤫" },
      { nl: "de straat", en: "the street", icon: "🛣️" },
      { nl: "genieten", en: "to enjoy", icon: "😌" },
      { nl: "hoog", en: "high", icon: "⬆️" },
      { nl: "laag", en: "low", icon: "⬇️" },
      { nl: "typisch", en: "typical" },
      { nl: "groot", en: "big" },
      { nl: "de kast", en: "the wardrobe", icon: "🗄️" },
      { nl: "de woonkamer", en: "the living room", icon: "🛋️" },
      { nl: "schoon", en: "clean", icon: "✨" },
      { nl: "vuil", en: "dirty" },
      { nl: "de waslijn", en: "the clothesline", icon: "🧺" },
      { nl: "de moeder", en: "the mother", icon: "👩" },
      { nl: "het raam", en: "the window", icon: "🪟" },
      { nl: "lief", en: "lovely", icon: "❤️" },
      { nl: "stout", en: "naughty", icon: "😈" },
      { nl: "slapen", en: "to sleep", icon: "😴" },
      { nl: "het hok", en: "here: the dog house" },
      { nl: "vies", en: "1. disgusting 2. dirty", icon: "🤢" },
      { nl: "maken", en: "to make", icon: "🛠️" },
      { nl: "lekker", en: "yummy, tasty", icon: "😋" },
      { nl: "de taart", en: "the pie", icon: "🎂" },
      { nl: "laf", en: "cowardly" },
      { nl: "het meervoud", en: "plural" },
      { nl: "de brief", en: "the letter", icon: "✉️" },
      { nl: "de roos", en: "the rose", icon: "🌹" },
      { nl: "de kantine", en: "the canteen" },
      { nl: "het tijdschrift", en: "the magazine", icon: "📰" },
      { nl: "de fiets", en: "the bike", icon: "🚲" },
      { nl: "de tekening", en: "the drawing", icon: "🎨" },
      { nl: "de boodschap", en: "1. the message 2. the purchase (groceries)", icon: "🛍️" },
      { nl: "de jas", en: "the jacket", icon: "🧥" },
      { nl: "de pet", en: "the cap", icon: "🧢" },
      { nl: "de tas", en: "the bag", icon: "👜" },
      { nl: "de klok", en: "the clock", icon: "🕐" },

      // Everyday objects & places
      { nl: "de kus", en: "the kiss", icon: "💋" },
      { nl: "de tomaat", en: "the tomato", icon: "🍅" },
      { nl: "de boom", en: "the tree", icon: "🌳" },
      { nl: "de schaar", en: "the pair of scissors", icon: "✂️" },
      { nl: "de persoon", en: "the person", icon: "🧑" },
      { nl: "de minuut", en: "the minute", icon: "⏱️" },
      { nl: "de jurk", en: "the dress", icon: "👗" },
      { nl: "de vork", en: "the fork", icon: "🍴" },
      { nl: "de mand", en: "the basket", icon: "🧺" },
      { nl: "de raaf", en: "the raven", icon: "🐦‍⬛" },
      { nl: "de kaas", en: "the cheese", icon: "🧀" },
      { nl: "de tafel", en: "the table" },
      { nl: "de agenda", en: "the agenda", icon: "📅" },
      { nl: "de courgette", en: "the zucchini / courgette", icon: "🥒" },
      { nl: "de vakantie", en: "the holiday, the vacation", icon: "🏖️" },
      { nl: "de regel", en: "the rule" },
      { nl: "de modem", en: "the modem", icon: "📡" },
      { nl: "het teken", en: "the sign" },
      { nl: "de kamer", en: "the room", icon: "🚪" },
      { nl: "de camera", en: "the camera", icon: "📷" },
      { nl: "de taxi", en: "the cab", icon: "🚕" },
      { nl: "de foto", en: "the photo", icon: "📸" },
      { nl: "de paraplu", en: "the umbrella", icon: "☂️" },
      { nl: "de school", en: "the school", icon: "🏫" },
      { nl: "de sportschool", en: "the gym", icon: "🏋️" },
      { nl: "om", en: "at (+time)" },
      { nl: "het huiswerk", en: "the homework", icon: "📝" },
      { nl: "de plaats", en: "the place" },
      { nl: "de richting", en: "the direction" },
      { nl: "de tijd", en: "the time", icon: "⏰" },
      { nl: "de winkel", en: "the shop", icon: "🏬" },
      { nl: "het bos", en: "the forest", icon: "🌲" },
      { nl: "het geluid", en: "the sound", icon: "🔊" },
      { nl: "de lamp", en: "the lamp", icon: "💡" },
      { nl: "hangen", en: "to hang" },
      { nl: "boven", en: "above", icon: "⬆️" },
      { nl: "de schoen", en: "the shoe", icon: "👟" },
      { nl: "onder", en: "under", icon: "⬇️" },
      { nl: "voor", en: "in front of" },
      { nl: "achter", en: "behind" },
      { nl: "naast", en: "next to" },
      { nl: "het examen", en: "the exam", icon: "📝" },

      // Doing groceries
      { nl: "boodschappen doen", en: "to do grocery shopping", icon: "🛒" },
      { nl: "kopen", en: "to buy", icon: "🛍️" },
      { nl: "vinden", en: "to find" },
      { nl: "de kost", en: "the food" },
      { nl: "de kosten", en: "the cost", icon: "💰" },
      { nl: "de aardappel", en: "the potato", icon: "🥔" },
      { nl: "het vlees", en: "the meat", icon: "🥩" },
      { nl: "zin hebben (in)", en: "to be in the mood for" },

      // At the greengrocer / butcher
      { nl: "de groenteboer", en: "the greengrocer", icon: "🥬" },
      { nl: "de slager", en: "the butcher", icon: "🥩" },
      { nl: "vers", en: "fresh", icon: "✨" },
      { nl: "groen", en: "green", icon: "🟢" },
      { nl: "mogen", en: "to be allowed to" },
      { nl: "alstublieft", en: "1. here you are 2. please", icon: "🙏" },

      // Quantities & small talk while shopping
      { nl: "kosten", en: "to cost", icon: "💰" },
      { nl: "even", en: "just (a short while)" },
      { nl: "gram", en: "gram" },
      { nl: "anders", en: "otherwise" },
      { nl: "iets", en: "1. something 2. some" },

      // Paying & more food
      { nl: "meneer", en: "mister", icon: "🎩" },
      { nl: "prachtig", en: "beautiful", icon: "✨" },
      { nl: "alles", en: "everything" },
      { nl: "betalen", en: "to pay", icon: "💳" },
      { nl: "de biefstuk", en: "the steak", icon: "🥩" },
      { nl: "meer", en: "more" },
      { nl: "het probleem", en: "the problem", icon: "❗" },
      { nl: "de rest", en: "the rest" },
      { nl: "het toetje", en: "the dessert", icon: "🍮" },
      { nl: "de supermarkt", en: "the supermarket", icon: "🛒" },
      { nl: "het winkelmandje", en: "the shopping cart", icon: "🛒" },
      { nl: "het pak", en: "the carton", icon: "📦" },
      { nl: "de vla", en: "the custard", icon: "🍮" },

      // At the checkout
      { nl: "de yoghurt", en: "the yoghurt", icon: "🥣" },
      { nl: "de fles", en: "the bottle", icon: "🍾" },
      { nl: "de limonadesiroop", en: "the lemonade syrup", icon: "🧃" },
      { nl: "pinnen", en: "to pay with a debit card", icon: "💳" },
      { nl: "de kassa", en: "the checkout", icon: "🛒" },

      // A recipe
      { nl: "bereiden", en: "to prepare", icon: "👩‍🍳" },
      { nl: "het recept", en: "1. the recipe 2. the prescription", icon: "📋" },
      { nl: "de rookworst", en: "the smoked sausage", icon: "🌭" },
      { nl: "de melk", en: "the milk", icon: "🥛" },
      { nl: "de boter", en: "the butter", icon: "🧈" },
      { nl: "de mosterd", en: "the mustard" },
      { nl: "de spekjes", en: "the bacon", icon: "🥓" },
      { nl: "de eetlepel", en: "the tablespoon", icon: "🥄" },
      { nl: "de worst", en: "the sausage", icon: "🌭" },
      { nl: "afgieten", en: "to drain off" },
      { nl: "schillen", en: "to peel" },
      { nl: "stampen", en: "to mash" },
      { nl: "toevoegen", en: "to add", icon: "➕" },
    ],
  },

  {
    id: 4,
    title: "Lesson 4 — Hoofdstuk 4: Koken",
    words: [
      // Friends, family & get-togethers
      { nl: "langzaam", en: "slow", icon: "🐢" },
      { nl: "de vriend", en: "the friend", icon: "👬" },
      { nl: "mijn vriend", en: "my (boy)friend", icon: "💑" },
      { nl: "het schatje", en: "the darling", icon: "🥰" },
      { nl: "organiseren", en: "to organise" },
      { nl: "de familie", en: "the family", icon: "👨‍👩‍👧‍👦" },
      { nl: "het etentje", en: "the dinner", icon: "🍽️" },
      { nl: "het feestje", en: "the party", icon: "🎉" },
      { nl: "een eindje", en: "a small distance" },
      { nl: "het jongetje", en: "the little boy", icon: "👦" },
      { nl: "het spel", en: "the game", icon: "🎮" },
      { nl: "de vriendin", en: "the (girl)friend", icon: "👭" },
      { nl: "de hoek", en: "the corner" },
      { nl: "de kroeg", en: "the café", icon: "🍺" },
      { nl: "het biertje", en: "the glass of beer", icon: "🍺" },
      { nl: "de woning", en: "the house", icon: "🏠" },
      { nl: "de pauze", en: "the break", icon: "⏸️" },
      { nl: "het papier", en: "the paper", icon: "📄" },
      { nl: "de bril", en: "the pair of glasses", icon: "👓" },

      // Fractions & amounts
      { nl: "een kwart", en: "a quarter" },
      { nl: "het zeeniveau", en: "the sea level", icon: "🌊" },
      { nl: "de Nederlander", en: "the Dutch (citizen)", icon: "🇳🇱" },
      { nl: "de helft", en: "the half" },
      { nl: "religieus", en: "religious" },
      { nl: "bijna", en: "almost" },
      { nl: "bestaan (uit)", en: "to consist (of)" },
      { nl: "een vijfde", en: "one fifth" },
      { nl: "het water", en: "the water", icon: "💧" },
      { nl: "driekwart", en: "three quarters" },

      // Grammar (gender) & random nouns
      { nl: "de bloembol", en: "the flower bulb", icon: "🌷" },
      { nl: "de wereld", en: "the world", icon: "🌍" },
      { nl: "spannend", en: "thrilling", icon: "😬" },
      { nl: "de bal", en: "the ball", icon: "⚽" },
      { nl: "rond", en: "round", icon: "⭕" },
      { nl: "mannelijk", en: "masculine", icon: "🚹" },
      { nl: "vrouwelijk", en: "feminine", icon: "🚺" },
      { nl: "moeilijk", en: "difficult", icon: "😓" },
      { nl: "de bus", en: "the bus", icon: "🚌" },
      { nl: "onzijdig", en: "neuter" },
      { nl: "het podium", en: "the stage", icon: "🎤" },
      { nl: "het orkest", en: "the orchestra", icon: "🎻" },
      { nl: "het paard", en: "the horse", icon: "🐴" },
      { nl: "de wei", en: "the grasslands", icon: "🌾" },

      // The apartment & kitchen
      { nl: "het appartement", en: "the apartment", icon: "🏢" },
      { nl: "de verdieping", en: "the floor" },
      { nl: "de keer", en: "the time" },
      { nl: "helpen", en: "to help", icon: "🆘" },
      { nl: "lusten", en: "to like (food/drink)", icon: "😋" },
      { nl: "de koelkast", en: "the fridge", icon: "🧊" },
      { nl: "de plank", en: "the shelf" },
      { nl: "de wijn", en: "the wine", icon: "🍷" },
      { nl: "proost", en: "cheers", icon: "🥂" },
      { nl: "eerst", en: "first" },

      // Cooking
      { nl: "het mes", en: "the knife", icon: "🔪" },
      { nl: "snijden", en: "to cut", icon: "✂️" },
      { nl: "de plak", en: "the slice" },
      { nl: "de oven", en: "the oven", icon: "🔥" },
      { nl: "de pan", en: "the pan", icon: "🍳" },
      { nl: "zetten", en: "to put" },
      { nl: "het vuur", en: "the fire", icon: "🔥" },
      { nl: "wachten", en: "to wait", icon: "⏳" },
      { nl: "ondertussen", en: "meanwhile" },
      { nl: "Italië", en: "Italy", icon: "🇮🇹" },
      { nl: "altijd", en: "always" },
      { nl: "voetbal kijken", en: "to watch football", icon: "⚽" },
      { nl: "tegen", en: "against" },
      { nl: "gaar", en: "done (cooked)" },
      { nl: "halen", en: "to pick up" },
      { nl: "pakken", en: "to grab" },
      { nl: "de koekenpan", en: "the frying pan", icon: "🍳" },
      { nl: "het stuk", en: "the piece" },

      // Food & drink
      { nl: "de biet", en: "the beetroot" },
      { nl: "de soep", en: "the soup", icon: "🍲" },
      { nl: "de zure room", en: "the sour cream" },
      { nl: "misschien", en: "maybe", icon: "🤷" },
      { nl: "zoeken", en: "to search", icon: "🔍" },
      { nl: "pas", en: "1. just, only 2. really" },
      { nl: "schrikken", en: "to scare", icon: "😱" },
      { nl: "de augurk", en: "the pickle", icon: "🥒" },
      { nl: "de grapefruit", en: "the grapefruit", icon: "🍊" },
      { nl: "de witlof", en: "the chicory" },
      { nl: "de croissant", en: "the croissant", icon: "🥐" },
      { nl: "de honing", en: "the honey", icon: "🍯" },
      { nl: "de chips", en: "the chips", icon: "🍟" },
      { nl: "de haring", en: "the herring", icon: "🐟" },
      { nl: "de nootjes", en: "the nuts", icon: "🥜" },
    ],
  },

  {
    id: 5,
    title: "Lesson 5 — Hoofdstuk 5: Het huis",
    words: [
      // Family & possessions
      { nl: "je, jouw", en: "your (singular, informal)" },
      { nl: "de broer", en: "the brother", icon: "👦" },
      { nl: "uw", en: "your (singular, polite)" },
      { nl: "de sleutel", en: "the key", icon: "🔑" },
      { nl: "haar", en: "her" },
      { nl: "ziek", en: "ill", icon: "🤒" },
      { nl: "ons, onze", en: "our" },
      { nl: "het kleinkind", en: "the grandchild", icon: "👶" },
      { nl: "de cd", en: "the cd", icon: "💿" },
      { nl: "hun", en: "their" },
      { nl: "de ouder", en: "the parent", icon: "👪" },
      { nl: "aardig", en: "nice, friendly", icon: "😊" },
      { nl: "slim", en: "clever", icon: "🧠" },
      { nl: "blauw", en: "blue", icon: "🔵" },
      { nl: "de trui", en: "the sweater", icon: "👕" },
      { nl: "het bed", en: "the bed", icon: "🛏️" },
      { nl: "zwart", en: "black", icon: "⚫" },
      { nl: "kwijt (zijn)", en: "(to have) lost" },
      { nl: "rood", en: "red", icon: "🔴" },
      { nl: "deze", en: "this" },
      { nl: "die", en: "that" },
      { nl: "erg", en: "very" },
      { nl: "duur", en: "expensive", icon: "💰" },
      { nl: "bestellen", en: "to order", icon: "🛒" },

      // Celebrating & everyday life
      { nl: "tijdens", en: "during" },
      { nl: "vieren", en: "to celebrate", icon: "🎉" },
      { nl: "de verjaardag", en: "the birthday", icon: "🎂" },
      { nl: "het licht", en: "the light", icon: "💡" },
      { nl: "de muziek", en: "the music", icon: "🎵" },
      { nl: "de ballon", en: "the balloon", icon: "🎈" },
      { nl: "na", en: "after" },
      { nl: "de nacht", en: "the night", icon: "🌙" },
      { nl: "volgens", en: "according to" },
      { nl: "de gast", en: "the guest", icon: "🧑‍🤝‍🧑" },
      { nl: "naar huis gaan", en: "to go home", icon: "🏠" },
      { nl: "behalve", en: "except for" },
      { nl: "zonder", en: "without" },
      { nl: "de pagina", en: "the page", icon: "📄" },
      { nl: "de doos", en: "the box, the case", icon: "📦" },
      { nl: "het hoofdkantoor", en: "the head office", icon: "🏢" },
      { nl: "laten", en: "to let" },
      { nl: "laten zien", en: "to show" },

      // The living room & kitchen
      { nl: "de stoel", en: "the chair", icon: "🪑" },
      { nl: "de bank", en: "1. the couch 2. the bank", icon: "🛋️" },
      { nl: "het telefoonnummer", en: "the phone number", icon: "📞" },
      { nl: "de trofee", en: "the trophy", icon: "🏆" },
      { nl: "het uitzicht", en: "the view", icon: "🌅" },
      { nl: "Kom verder.", en: "Come in." },
      { nl: "de keuken", en: "1. the kitchen 2. the cuisine", icon: "🍳" },
      { nl: "het fornuis", en: "the stove", icon: "🔥" },
      { nl: "het aanrecht", en: "the kitchen counter" },
      { nl: "de magnetron", en: "the microwave oven" },
      { nl: "de bijkeuken", en: "the scullery" },
      { nl: "helaas", en: "unfortunately" },
      { nl: "de wasmachine", en: "the washing machine", icon: "🧺" },
      { nl: "kapot", en: "broken", icon: "💔" },
      { nl: "de was", en: "the laundry", icon: "🧺" },
      { nl: "brengen", en: "to bring" },
      { nl: "de kleding", en: "the clothing", icon: "👕" },
      { nl: "Dat meen je niet!", en: "You are kidding me!", icon: "😲" },
      { nl: "menen", en: "to mean" },
      { nl: "wel", en: "opposite of not" },

      // Around the house
      { nl: "terug", en: "back" },
      { nl: "de gang", en: "the hallway" },
      { nl: "de wc", en: "the toilet", icon: "🚽" },
      { nl: "de badkamer", en: "the bathroom", icon: "🛁" },
      { nl: "de slaapkamer", en: "the bedroom", icon: "🛏️" },
      { nl: "het tweepersoonsbed", en: "the double bed", icon: "🛏️" },
      { nl: "alleen", en: "1. alone 2. only" },
      { nl: "Je weet maar nooit!", en: "You never know!" },
      { nl: "nooit", en: "never" },
      { nl: "de bel", en: "the bell", icon: "🔔" },

      // At the bar
      { nl: "aan de bar", en: "at the bar", icon: "🍸" },
      { nl: "de tap", en: "the beer tap", icon: "🍺" },
      { nl: "de ober", en: "the waiter", icon: "🧑‍🍳" },
      { nl: "de wedstrijd", en: "the game", icon: "⚽" },
      { nl: "verliezen", en: "to lose" },
      { nl: "verdrietig", en: "sad", icon: "😢" },
      { nl: "daarom", en: "that's why" },
      { nl: "vol", en: "full" },
    ],
  },

  {
    id: 6,
    title: "Lesson 6 — Hoofdstuk 6: De vakantie",
    words: [
      // Nature, numbers & everyday words
      { nl: "'s ochtends", en: "in the morning", icon: "🌅" },
      { nl: "de suiker", en: "the sugar" },
      { nl: "de tarwe", en: "the wheat", icon: "🌾" },
      { nl: "de regen", en: "the rain", icon: "🌧️" },
      { nl: "de zonneschijn", en: "the sunshine", icon: "☀️" },
      { nl: "rollen", en: "to roll" },
      { nl: "de minister-president", en: "the prime minister" },
      { nl: "de dokter", en: "the doctor", icon: "👨‍⚕️" },
      { nl: "een miljoen", en: "a million" },
      { nl: "een miljard", en: "a billion" },
      { nl: "elk", en: "each" },
      { nl: "ieder", en: "each" },
      { nl: "het snoep", en: "the candy", icon: "🍬" },
      { nl: "het oor", en: "the ear", icon: "👂" },
      { nl: "de staart", en: "the tail" },
      { nl: "het dorp", en: "the village", icon: "🏘️" },
      { nl: "iemand", en: "someone" },
      { nl: "ergens", en: "somewhere" },
      { nl: "ooit", en: "some day, ever" },
      { nl: "op bezoek komen", en: "to visit (someone)" },
      { nl: "de verrassing", en: "the surprise", icon: "🎁" },
      { nl: "niets", en: "nothing" },
      { nl: "leeg", en: "empty" },
      { nl: "de spullen", en: "the stuff, the things" },
      { nl: "nergens", en: "nowhere" },
      { nl: "sorry", en: "sorry, I'm sorry", icon: "😔" },
      { nl: "de provincie", en: "the province" },
      { nl: "het leven", en: "the life" },
      { nl: "volgend", en: "next" },
      { nl: "het centrum", en: "1. the centre 2. the city centre" },

      // Holidays & the outdoors
      { nl: "dag", en: "hello", icon: "👋" },
      { nl: "kamperen", en: "to camp (out)", icon: "⛺" },
      { nl: "de strandvakantie", en: "the beach holiday", icon: "🏖️" },
      { nl: "de zomercursus", en: "the summer course" },
      { nl: "klinken", en: "to sound" },
      { nl: "het platteland", en: "the countryside", icon: "🌾" },
      { nl: "barbecueën", en: "to barbecue", icon: "🍖" },
      { nl: "de natuur", en: "the nature", icon: "🌳" },
      { nl: "het advies", en: "the advice" },

      // Booking & paying
      { nl: "boeken", en: "to book", icon: "📅" },
      { nl: "de website", en: "the website", icon: "🌐" },
      { nl: "een paar", en: "1. a pair, two 2. a few" },
      { nl: "de organisatie", en: "the organisation" },
      { nl: "beantwoorden", en: "to answer" },
      { nl: "met plezier", en: "with pleasure", icon: "😊" },
      { nl: "precies", en: "exactly" },
      { nl: "het vakantiepark", en: "the holiday park", icon: "🏕️" },
      { nl: "de prijs", en: "the price", icon: "🏷️" },
      { nl: "de offerte", en: "the quotation" },
      { nl: "het formulier", en: "the form", icon: "📝" },
      { nl: "de gegevens", en: "the data" },
      { nl: "de bankoverschrijving", en: "the bank transfer", icon: "💳" },
      { nl: "de creditcard", en: "the credit card", icon: "💳" },
      { nl: "online", en: "online", icon: "💻" },
      { nl: "het betaalsysteem", en: "the payment system", icon: "💳" },
      { nl: "duidelijk", en: "clear" },

      // Registering & accommodation
      { nl: "inschrijven", en: "to enrol", icon: "✍️" },
      { nl: "het geslacht", en: "the gender" },
      { nl: "de voorletter", en: "the initial (letter)" },
      { nl: "het tussenvoegsel", en: "the surname prefix" },
      { nl: "het huisnummer", en: "the house number", icon: "🏠" },
      { nl: "de toevoeging", en: "the addition" },
      { nl: "de postcode", en: "the postal code", icon: "📮" },
      { nl: "de woonplaats", en: "the city of residence", icon: "🏠" },
      { nl: "het e-mailadres", en: "the email address", icon: "📧" },
      { nl: "het niveau", en: "the level" },
      { nl: "de beginner", en: "the beginner", icon: "🌱" },
      { nl: "de accommodatie", en: "the accommodation", icon: "🏨" },
      { nl: "de gedeelde kamer", en: "the shared room", icon: "🛏️" },
      { nl: "de eigen kamer", en: "the private room", icon: "🚪" },
      { nl: "de studio", en: "the studio" },
      { nl: "via", en: "via (through)" },
      { nl: "namelijk", en: "namely" },
    ],
  },

  {
    id: 7,
    title: "Lesson 7 — Hoofdstuk 7: Het openbaar vervoer",
    words: [
      // Getting around & everyday phrases
      { nl: "de hulp", en: "the help", icon: "🆘" },
      { nl: "nodig", en: "required" },
      { nl: "nodig hebben", en: "to need" },
      { nl: "het openbaar vervoer", en: "the public transport", icon: "🚌" },
      { nl: "de ov-chipkaart", en: "the public transport chip card", icon: "💳" },

      // Comparisons & everyday talk
      { nl: "de afspraak", en: "1. the appointment 2. the agreement", icon: "📅" },
      { nl: "het koekje", en: "the cookie, the biscuit", icon: "🍪" },
      { nl: "regenen", en: "to rain", icon: "🌧️" },
      { nl: "roken", en: "to smoke", icon: "🚬" },
      { nl: "de acteur", en: "the actor", icon: "🎭" },
      { nl: "met vakantie gaan", en: "to go on vacation", icon: "🏖️" },
      { nl: "op vakantie gaan", en: "to go on vacation", icon: "🏖️" },
      { nl: "de bioscoop", en: "the cinema", icon: "🎬" },
      { nl: "de schuur", en: "the shed", icon: "🏚️" },
      { nl: "niet graag (+werkwoord)", en: "don't like to (+verb)" },
      { nl: "vertrekken", en: "to leave" },
      { nl: "per week", en: "per week" },
      { nl: "twee keer", en: "two times" },
      { nl: "ver", en: "far" },
      { nl: "niet zo ver", en: "not that far" },
      { nl: "een half uur", en: "half an hour", icon: "⏱️" },
      { nl: "genoeg", en: "enough" },
      { nl: "het model", en: "the model" },
      { nl: "mooier dan", en: "more beautiful than" },
      { nl: "beter", en: "better" },
      { nl: "het best", en: "the best" },
      { nl: "weinig", en: "little, few" },
      { nl: "de kilo", en: "the kilogram", icon: "⚖️" },
      { nl: "het pond", en: "the pound", icon: "⚖️" },
      { nl: "minder", en: "less" },
      { nl: "het ons", en: "the ounce", icon: "⚖️" },
      { nl: "het minst", en: "the fewest, the least amount" },
      { nl: "het meest", en: "the most" },
      { nl: "even groot als", en: "as tall as" },

      // Air & road travel
      { nl: "de auto", en: "the car", icon: "🚗" },
      { nl: "het vliegtuig", en: "the airplane", icon: "✈️" },
      { nl: "landen", en: "to land", icon: "🛬" },
      { nl: "Schiphol", en: "Amsterdam Airport", icon: "✈️" },
      { nl: "het vliegveld", en: "the airport", icon: "✈️" },
      { nl: "het kaartje", en: "the ticket", icon: "🎫" },
      { nl: "de automaat", en: "the machine", icon: "🏧" },

      // Public transport
      { nl: "de metro", en: "the subway", icon: "🚇" },
      { nl: "de tram", en: "the tram", icon: "🚊" },
      { nl: "het saldo", en: "the balance", icon: "💰" },
      { nl: "opwaarderen", en: "to top up (credit)", icon: "💳" },
      { nl: "bijvoorbeeld", en: "for example" },
      { nl: "simpel", en: "simple" },
      { nl: "inchecken", en: "to check in", icon: "✅" },
      { nl: "uitchecken", en: "to check out", icon: "✅" },
      { nl: "de reis", en: "the journey, trip", icon: "🧳" },
      { nl: "dus", en: "so" },
      { nl: "makkelijk", en: "easy" },
      { nl: "lijken", en: "to seem" },
      { nl: "toevallig", en: "coincidental" },
      { nl: "het perron", en: "the platform", icon: "🚉" },
      { nl: "de intercity", en: "the intercity", icon: "🚆" },
      { nl: "duren", en: "to last", icon: "⏳" },
      { nl: "snel", en: "fast", icon: "💨" },
      { nl: "in principe", en: "in principle (basically)" },
      { nl: "de file", en: "the traffic jam", icon: "🚦" },

      // Planning a trip
      { nl: "het vervoermiddel", en: "means of transport" },
      { nl: "de veerboot", en: "the ferry boat", icon: "⛴️" },
      { nl: "het vertrek", en: "the departure" },
      { nl: "de aankomst", en: "the arrival" },
      { nl: "de optie", en: "the option" },
      { nl: "plannen", en: "to plan", icon: "🗓️" },
      { nl: "wijzigen", en: "to change" },
      { nl: "overstappen", en: "to change over", icon: "🔄" },
      { nl: "de overstap", en: "the changeover", icon: "🔄" },
      { nl: "totaal", en: "total" },
      { nl: "het spoor", en: "the platform", icon: "🛤️" },
      { nl: "arriveren", en: "to arrive" },
      { nl: "het milieu", en: "the environment", icon: "🌍" },
    ],
  },
];
