// Dutch flashcard data.
//
// HOW TO ADD A NEW LESSON:
// Just copy the block below (from "{" to "},") and paste it as a new
// entry in the LESSONS array. Give it the next id/title, then fill in
// "words" as { nl: "...", en: "..." } pairs. That's it — the app picks
// up new lessons automatically, no other code changes needed.

const LESSONS = [
  {
    id: 1,
    title: "Lesson 1 — Introductie & De kennismaking",
    words: [
      // People & everyday things
      { nl: "de, het", en: "the" },
      { nl: "een", en: "a" },
      { nl: "de man", en: "the man" },
      { nl: "de vrouw", en: "the woman" },
      { nl: "de baby", en: "the baby" },
      { nl: "de hond", en: "the dog" },
      { nl: "de kat", en: "the cat" },
      { nl: "het dier", en: "the animal" },
      { nl: "de student", en: "the student" },
      { nl: "de docent", en: "the teacher" },
      { nl: "de les", en: "the lesson" },
      { nl: "de pen", en: "the pen" },
      { nl: "de tekst", en: "the text" },
      { nl: "het theater", en: "the theatre" },
      { nl: "het meisje", en: "the girl" },
      { nl: "het kind", en: "the child" },
      { nl: "het konijn", en: "the rabbit" },
      { nl: "het boek", en: "the book" },
      { nl: "het land", en: "the country" },
      { nl: "het adres", en: "the address" },
      { nl: "het antwoord", en: "the answer" },
      { nl: "het huis", en: "the house" },
      { nl: "de tablet", en: "the tablet" },
      { nl: "de smartphone", en: "the smartphone" },
      { nl: "het tennis", en: "the tennis" },
      { nl: "Veel succes!", en: "Good luck!" },

      // Names, cities, countries & languages
      { nl: "de naam", en: "the name" },
      { nl: "de voornaam", en: "the first name" },
      { nl: "de achternaam", en: "the surname" },
      { nl: "de stad", en: "the city" },
      { nl: "de taal", en: "the language" },
      { nl: "Nederland", en: "the Netherlands" },
      { nl: "het Nederlands", en: "the Dutch language" },
      { nl: "Duitsland", en: "Germany" },
      { nl: "het Duits", en: "the German language" },
      { nl: "Amerika", en: "America" },
      { nl: "het Engels", en: "the English language" },
      { nl: "China", en: "China" },
      { nl: "het Chinees", en: "the Chinese language" },
      { nl: "Rusland", en: "Russia" },
      { nl: "het Russisch", en: "the Russian language" },
      { nl: "Frankrijk", en: "France" },
      { nl: "het Frans", en: "the French language" },
      { nl: "Spanje", en: "Spain" },
      { nl: "Spaans", en: "Spanish" },

      // Pronouns
      { nl: "ik", en: "I" },
      { nl: "jij / je", en: "you (informal)" },
      { nl: "u", en: "you (polite)" },
      { nl: "hij", en: "he" },
      { nl: "zij / ze", en: "she" },
      { nl: "wij / we", en: "we" },
      { nl: "jullie", en: "you (plural)" },

      // Time: days, months, seasons
      { nl: "de dag", en: "the day" },
      { nl: "de week", en: "the week" },
      { nl: "de maand", en: "the month" },
      { nl: "het jaar", en: "the year" },
      { nl: "maandag", en: "Monday" },
      { nl: "dinsdag", en: "Tuesday" },
      { nl: "woensdag", en: "Wednesday" },
      { nl: "donderdag", en: "Thursday" },
      { nl: "vrijdag", en: "Friday" },
      { nl: "zaterdag", en: "Saturday" },
      { nl: "zondag", en: "Sunday" },
      { nl: "januari", en: "January" },
      { nl: "februari", en: "February" },
      { nl: "maart", en: "March" },
      { nl: "april", en: "April" },
      { nl: "mei", en: "May" },
      { nl: "juni", en: "June" },
      { nl: "juli", en: "July" },
      { nl: "augustus", en: "August" },
      { nl: "september", en: "September" },
      { nl: "oktober", en: "October" },
      { nl: "november", en: "November" },
      { nl: "december", en: "December" },
      { nl: "het seizoen", en: "the season" },
      { nl: "de lente", en: "the spring" },
      { nl: "de zomer", en: "the summer" },
      { nl: "de herfst", en: "the autumn" },
      { nl: "de winter", en: "the winter" },

      // Verbs
      { nl: "het werkwoord", en: "the verb" },
      { nl: "kijken", en: "to watch" },
      { nl: "de televisie", en: "the television" },
      { nl: "werken", en: "to work" },
      { nl: "op", en: "at / on" },
      { nl: "de universiteit", en: "the university" },
      { nl: "antwoorden", en: "to answer" },
      { nl: "de vraag", en: "the question" },
      { nl: "lopen", en: "to walk" },
      { nl: "leren", en: "to learn" },
      { nl: "vertellen", en: "to tell" },
      { nl: "wonen", en: "to live" },
      { nl: "in", en: "in" },
      { nl: "spreken", en: "to speak" },
      { nl: "al", en: "already" },
      { nl: "lezen", en: "to read" },
      { nl: "de krant", en: "the newspaper" },
      { nl: "geven", en: "to give" },
      { nl: "zitten", en: "to sit" },
      { nl: "buiten", en: "outside" },
      { nl: "hebben", en: "to have" },
      { nl: "zijn", en: "to be" },
      { nl: "sinds", en: "since" },
      { nl: "vanavond", en: "tonight" },
      { nl: "komen", en: "to come" },
      { nl: "uit", en: "from / out of" },
      { nl: "binnen", en: "inside" },
      { nl: "nu", en: "now" },
      { nl: "op dit moment", en: "at this moment" },

      // Greetings & meeting someone
      { nl: "ontmoeten", en: "to meet" },
      { nl: "hoi", en: "hi" },
      { nl: "wie", en: "who" },
      { nl: "aangenaam", en: "nice to meet you" },
      { nl: "Hoe heet jij?", en: "What is your name?" },
      { nl: "Ik heet...", en: "My name is..." },
      { nl: "en", en: "and" },
      { nl: "waar", en: "where" },
      { nl: "waar vandaan", en: "where from" },
      { nl: "een beetje", en: "a bit" },
      { nl: "wauw", en: "wow" },
      { nl: "veel", en: "much / many" },

      // Small talk phrases
      { nl: "welke", en: "which" },
      { nl: "Wat leuk!", en: "How nice!" },
      { nl: "ook", en: "too" },
      { nl: "doen", en: "to do" },
      { nl: "dat", en: "that" },
      { nl: "begrijpen", en: "to understand" },
      { nl: "mijn", en: "my" },
      { nl: "het beroep", en: "the profession" },
      { nl: "ja", en: "yes" },
      { nl: "de actrice", en: "the actress" },
      { nl: "Wat interessant!", en: "How interesting!" },
      { nl: "beginnen", en: "to begin" },
      { nl: "met", en: "with" },
      { nl: "dankjewel", en: "thank you" },
      { nl: "de koffie", en: "the coffee" },
      { nl: "alsjeblieft", en: "here you are / please" },
      { nl: "goed", en: "right / good" },
      { nl: "fout", en: "wrong / false" },

      // A story: guided tour
      { nl: "het verhaal", en: "the story" },
      { nl: "de rondleiding", en: "the guided tour" },
      { nl: "het werk", en: "the job" },
      { nl: "vandaag", en: "today" },
      { nl: "van", en: "from" },
      { nl: "het station", en: "the station" },
      { nl: "naar", en: "to" },
      { nl: "zeggen", en: "to say" },
      { nl: "dit", en: "this" },
      { nl: "het paleis", en: "the palace" },
      { nl: "vragen", en: "to ask" },
      { nl: "de koning", en: "the king" },
      { nl: "nee", en: "no" },
      { nl: "bij", en: "at" },
      { nl: "de vrijgezel", en: "the bachelor" },
      { nl: "maar", en: "but / only" },
      { nl: "geen", en: "no / none" },
      { nl: "verder", en: "further" },
      { nl: "leuk", en: "fun" },
      { nl: "over", en: "about" },
    ],
  },

  {
    id: 2,
    title: "Lesson 2 — Hoofdstuk 2: Vragen",
    words: [
      // Money & time
      { nl: "laat", en: "late" },
      { nl: "hoeveel", en: "how many / how much" },
      { nl: "het geld", en: "the money" },

      // Degree words & adjectives
      { nl: "spelen", en: "to play" },
      { nl: "heel", en: "1. very 2. whole" },
      { nl: "zeer", en: "very" },
      { nl: "klein", en: "small" },
      { nl: "nogal", en: "quite" },
      { nl: "boos", en: "angry" },
      { nl: "redelijk", en: "rather" },
      { nl: "knap", en: "handsome" },
      { nl: "hartstikke", en: "extremely" },
      { nl: "mooi", en: "beautiful" },
      { nl: "gisteren", en: "yesterday" },
      { nl: "morgen", en: "tomorrow" },
      { nl: "nieuw", en: "new" },
      { nl: "het woord", en: "the word" },
      { nl: "de film", en: "the movie" },

      // Time, place & grammar
      { nl: "zo", en: "soon" },
      { nl: "straks", en: "in a little while" },
      { nl: "binnenkort", en: "soon" },
      { nl: "Sinterklaas", en: "Dutch Santa Claus" },
      { nl: "daar", en: "there" },
      { nl: "hier", en: "here" },
      { nl: "liggen", en: "to lie (be located)" },
      { nl: "inversie", en: "inversion (grammar)" },
      { nl: "de tuin", en: "the garden" },
      { nl: "de kapper", en: "the hairdresser" },
      { nl: "drinken", en: "to drink" },
      { nl: "de stamppot", en: "the hotchpotch" },
      { nl: "moeten", en: "to have to, must" },
      { nl: "klaar", en: "ready" },
      { nl: "het vraagwoord", en: "the question word" },

      // Market, questions & everyday life
      { nl: "de markt", en: "the market" },
      { nl: "de kinderen", en: "the children" },
      { nl: "het bezoek", en: "1. visit 2. guests" },
      { nl: "vaak", en: "often" },
      { nl: "fietsen", en: "to cycle" },
      { nl: "lesgeven", en: "to teach" },
      { nl: "wat", en: "what" },
      { nl: "je adres", en: "your address" },
      { nl: "aan", en: "to" },
      { nl: "welk, welke", en: "which" },
      { nl: "gebruiken", en: "to use" },
      { nl: "wanneer", en: "when" },
      { nl: "de jongen", en: "the boy" },
      { nl: "de oefening", en: "the exercise" },
      { nl: "jarig zijn", en: "to have a birthday" },
      { nl: "plat", en: "flat" },
      { nl: "hoe heten", en: "how ... called (e.g. Hoe heet jij? = What are you called?)" },

      // A phone call
      { nl: "bellen", en: "to call" },
      { nl: "hallo", en: "hello" },
      { nl: "Hoe gaat het met jou?", en: "How are you?" },
      { nl: "jou", en: "you" },
      { nl: "de roman", en: "the novel" },
      { nl: "waarom", en: "why" },
      { nl: "gewoon", en: "normal / just" },
      { nl: "weten", en: "to know" },
      { nl: "nog", en: "still / yet" },
      { nl: "niet", en: "not" },
      { nl: "eten", en: "to eat" },
      { nl: "het idee", en: "the idea" },
      { nl: "mij", en: "me" },
      { nl: "Goed idee!", en: "Good idea!" },
      { nl: "koken", en: "to cook" },
      { nl: "thuis", en: "at home" },
      { nl: "willen", en: "to want" },
      { nl: "Weet je wat?", en: "You know what?" },
      { nl: "samen", en: "together" },
      { nl: "daarna", en: "then / after that" },
      { nl: "tot", en: "until" },
      { nl: "nemen", en: "to take" },
      { nl: "de trein", en: "the train" },
      { nl: "meteen", en: "immediately" },
      { nl: "prima", en: "fine" },
      { nl: "de buurt", en: "the neighbourhood" },
      { nl: "de kilometer", en: "the kilometre" },
      { nl: "het Centraal Station", en: "the Central Station" },
      { nl: "ongeveer", en: "approximately" },
      { nl: "dan", en: "then" },
      { nl: "zien", en: "to see" },
      { nl: "Tot straks!", en: "See you later!" },
      { nl: "doei", en: "bye" },

      // Wrapping up
      { nl: "door", en: "through" },
      { nl: "kennen", en: "to know" },
      { nl: "zuchten", en: "to sigh" },
      { nl: "kunnen", en: "1. to be able to 2. to be available" },
      { nl: "druk", en: "1. busy 2. crowded" },
      { nl: "de eeuw", en: "the century" },
      { nl: "het einde", en: "the end" },
    ],
  },

  {
    id: 3,
    title: "Lesson 3 — Hoofdstuk 3: Boodschappen doen",
    words: [
      // Adjectives & opposites
      { nl: "lelijk", en: "ugly" },
      { nl: "slecht", en: "bad" },
      { nl: "lang", en: "1. long 2. tall (of people)" },
      { nl: "kort", en: "short" },
      { nl: "de tekst", en: "the text" },
      { nl: "de zin", en: "the sentence" },
      { nl: "zacht", en: "1. soft 2. slow" },
      { nl: "hard", en: "1. hard 2. loud 3. fast" },
      { nl: "de stem", en: "the voice" },
      { nl: "het kussen", en: "the pillow" },
      { nl: "de appel", en: "the apple" },
      { nl: "luisteren", en: "to listen" },
      { nl: "rijk", en: "rich" },
      { nl: "arm", en: "poor" },
      { nl: "honger hebben", en: "to be hungry" },
      { nl: "interessant", en: "interesting" },
      { nl: "saai", en: "boring" },
      { nl: "licht", en: "light" },
      { nl: "donker", en: "dark" },
      { nl: "het gezicht", en: "the face" },
      { nl: "koud", en: "cold" },
      { nl: "rijden", en: "to drive" },
      { nl: "oud", en: "old" },
      { nl: "staan", en: "to stand" },
      { nl: "de bakker", en: "the baker" },
      { nl: "bakken", en: "to bake" },
      { nl: "warm", en: "warm" },
      { nl: "het brood", en: "1. the bread 2. the loaf of bread" },
      { nl: "het ei", en: "the egg" },
      { nl: "gezellig", en: "cosy, sociable" },
      { nl: "ongezellig", en: "not cosy, cheerless" },
      { nl: "niemand", en: "nobody" },
      { nl: "het feest", en: "the party" },
      { nl: "dik", en: "fat" },
      { nl: "dun", en: "thin" },
      { nl: "de hamburger", en: "the hamburger" },
      { nl: "de wortel", en: "the carrot" },

      // More adjectives & things around the house
      { nl: "stom", en: "stupid" },
      { nl: "krijgen", en: "to get" },
      { nl: "de straf", en: "the punishment" },
      { nl: "rustig", en: "quiet" },
      { nl: "de straat", en: "the street" },
      { nl: "genieten", en: "to enjoy" },
      { nl: "hoog", en: "high" },
      { nl: "laag", en: "low" },
      { nl: "typisch", en: "typical" },
      { nl: "groot", en: "big" },
      { nl: "de kast", en: "the wardrobe" },
      { nl: "de woonkamer", en: "the living room" },
      { nl: "schoon", en: "clean" },
      { nl: "vuil", en: "dirty" },
      { nl: "de waslijn", en: "the clothesline" },
      { nl: "de moeder", en: "the mother" },
      { nl: "het raam", en: "the window" },
      { nl: "lief", en: "lovely" },
      { nl: "stout", en: "naughty" },
      { nl: "slapen", en: "to sleep" },
      { nl: "het hok", en: "here: the dog house" },
      { nl: "vies", en: "1. disgusting 2. dirty" },
      { nl: "maken", en: "to make" },
      { nl: "lekker", en: "yummy, tasty" },
      { nl: "de taart", en: "the pie" },
      { nl: "laf", en: "cowardly" },
      { nl: "het meervoud", en: "plural" },
      { nl: "de brief", en: "the letter" },
      { nl: "de roos", en: "the rose" },
      { nl: "de kantine", en: "the canteen" },
      { nl: "het tijdschrift", en: "the magazine" },
      { nl: "de fiets", en: "the bike" },
      { nl: "de tekening", en: "the drawing" },
      { nl: "de boodschap", en: "1. the message 2. the purchase (groceries)" },
      { nl: "de jas", en: "the jacket" },
      { nl: "de pet", en: "the cap" },
      { nl: "de tas", en: "the bag" },
      { nl: "de klok", en: "the clock" },

      // Everyday objects & places
      { nl: "de kus", en: "the kiss" },
      { nl: "de tomaat", en: "the tomato" },
      { nl: "de boom", en: "the tree" },
      { nl: "de schaar", en: "the pair of scissors" },
      { nl: "de persoon", en: "the person" },
      { nl: "de minuut", en: "the minute" },
      { nl: "de jurk", en: "the dress" },
      { nl: "de vork", en: "the fork" },
      { nl: "de mand", en: "the basket" },
      { nl: "de raaf", en: "the raven" },
      { nl: "de kaas", en: "the cheese" },
      { nl: "de tafel", en: "the table" },
      { nl: "de agenda", en: "the agenda" },
      { nl: "de courgette", en: "the zucchini / courgette" },
      { nl: "de vakantie", en: "the holiday, the vacation" },
      { nl: "de regel", en: "the rule" },
      { nl: "de modem", en: "the modem" },
      { nl: "het teken", en: "the sign" },
      { nl: "de kamer", en: "the room" },
      { nl: "de camera", en: "the camera" },
      { nl: "de taxi", en: "the cab" },
      { nl: "de foto", en: "the photo" },
      { nl: "de paraplu", en: "the umbrella" },
      { nl: "de school", en: "the school" },
      { nl: "de sportschool", en: "the gym" },
      { nl: "om", en: "at (+time)" },
      { nl: "het huiswerk", en: "the homework" },
      { nl: "de plaats", en: "the place" },
      { nl: "de richting", en: "the direction" },
      { nl: "de tijd", en: "the time" },
      { nl: "de winkel", en: "the shop" },
      { nl: "het bos", en: "the forest" },
      { nl: "het geluid", en: "the sound" },
      { nl: "de lamp", en: "the lamp" },
      { nl: "hangen", en: "to hang" },
      { nl: "boven", en: "above" },
      { nl: "de schoen", en: "the shoe" },
      { nl: "onder", en: "under" },
      { nl: "voor", en: "in front of" },
      { nl: "achter", en: "behind" },
      { nl: "naast", en: "next to" },
      { nl: "het examen", en: "the exam" },

      // Doing groceries
      { nl: "boodschappen doen", en: "to do grocery shopping" },
      { nl: "kopen", en: "to buy" },
      { nl: "vinden", en: "to find" },
      { nl: "de kost", en: "the food" },
      { nl: "de kosten", en: "the cost" },
      { nl: "de aardappel", en: "the potato" },
      { nl: "het vlees", en: "the meat" },
      { nl: "zin hebben (in)", en: "to be in the mood for" },

      // At the greengrocer / butcher
      { nl: "de groenteboer", en: "the greengrocer" },
      { nl: "de slager", en: "the butcher" },
      { nl: "vers", en: "fresh" },
      { nl: "groen", en: "green" },
      { nl: "mogen", en: "to be allowed to" },
      { nl: "alstublieft", en: "1. here you are 2. please" },

      // Quantities & small talk while shopping
      { nl: "kosten", en: "to cost" },
      { nl: "even", en: "just (a short while)" },
      { nl: "gram", en: "gram" },
      { nl: "anders", en: "otherwise" },
      { nl: "iets", en: "1. something 2. some" },

      // Paying & more food
      { nl: "meneer", en: "mister" },
      { nl: "prachtig", en: "beautiful" },
      { nl: "alles", en: "everything" },
      { nl: "betalen", en: "to pay" },
      { nl: "de biefstuk", en: "the steak" },
      { nl: "meer", en: "more" },
      { nl: "het probleem", en: "the problem" },
      { nl: "de rest", en: "the rest" },
      { nl: "het toetje", en: "the dessert" },
      { nl: "de supermarkt", en: "the supermarket" },
      { nl: "het winkelmandje", en: "the shopping cart" },
      { nl: "het pak", en: "the carton" },
      { nl: "de vla", en: "the custard" },

      // At the checkout
      { nl: "de yoghurt", en: "the yoghurt" },
      { nl: "de fles", en: "the bottle" },
      { nl: "de limonadesiroop", en: "the lemonade syrup" },
      { nl: "pinnen", en: "to pay with a debit card" },
      { nl: "de kassa", en: "the checkout" },

      // A recipe
      { nl: "bereiden", en: "to prepare" },
      { nl: "het recept", en: "1. the recipe 2. the prescription" },
      { nl: "de rookworst", en: "the smoked sausage" },
      { nl: "de melk", en: "the milk" },
      { nl: "de boter", en: "the butter" },
      { nl: "de mosterd", en: "the mustard" },
      { nl: "de spekjes", en: "the bacon" },
      { nl: "de eetlepel", en: "the tablespoon" },
      { nl: "de worst", en: "the sausage" },
      { nl: "afgieten", en: "to drain off" },
      { nl: "schillen", en: "to peel" },
      { nl: "stampen", en: "to mash" },
      { nl: "toevoegen", en: "to add" },
    ],
  },

  {
    id: 4,
    title: "Lesson 4 — Hoofdstuk 4: Koken",
    words: [
      // Friends, family & get-togethers
      { nl: "langzaam", en: "slow" },
      { nl: "de vriend", en: "the friend" },
      { nl: "mijn vriend", en: "my (boy)friend" },
      { nl: "het schatje", en: "the darling" },
      { nl: "organiseren", en: "to organise" },
      { nl: "de familie", en: "the family" },
      { nl: "het etentje", en: "the dinner" },
      { nl: "het feestje", en: "the party" },
      { nl: "een eindje", en: "a small distance" },
      { nl: "het jongetje", en: "the little boy" },
      { nl: "het spel", en: "the game" },
      { nl: "de vriendin", en: "the (girl)friend" },
      { nl: "de hoek", en: "the corner" },
      { nl: "de kroeg", en: "the café" },
      { nl: "het biertje", en: "the glass of beer" },
      { nl: "de woning", en: "the house" },
      { nl: "de pauze", en: "the break" },
      { nl: "het papier", en: "the paper" },
      { nl: "de bril", en: "the pair of glasses" },

      // Fractions & amounts
      { nl: "een kwart", en: "a quarter" },
      { nl: "het zeeniveau", en: "the sea level" },
      { nl: "de Nederlander", en: "the Dutch (citizen)" },
      { nl: "de helft", en: "the half" },
      { nl: "religieus", en: "religious" },
      { nl: "bijna", en: "almost" },
      { nl: "bestaan (uit)", en: "to consist (of)" },
      { nl: "een vijfde", en: "one fifth" },
      { nl: "het water", en: "the water" },
      { nl: "driekwart", en: "three quarters" },

      // Grammar (gender) & random nouns
      { nl: "de bloembol", en: "the flower bulb" },
      { nl: "de wereld", en: "the world" },
      { nl: "spannend", en: "thrilling" },
      { nl: "de bal", en: "the ball" },
      { nl: "rond", en: "round" },
      { nl: "mannelijk", en: "masculine" },
      { nl: "vrouwelijk", en: "feminine" },
      { nl: "moeilijk", en: "difficult" },
      { nl: "de bus", en: "the bus" },
      { nl: "onzijdig", en: "neuter" },
      { nl: "het podium", en: "the stage" },
      { nl: "het orkest", en: "the orchestra" },
      { nl: "het paard", en: "the horse" },
      { nl: "de wei", en: "the grasslands" },

      // The apartment & kitchen
      { nl: "het appartement", en: "the apartment" },
      { nl: "de verdieping", en: "the floor" },
      { nl: "de keer", en: "the time" },
      { nl: "helpen", en: "to help" },
      { nl: "lusten", en: "to like (food/drink)" },
      { nl: "de koelkast", en: "the fridge" },
      { nl: "de plank", en: "the shelf" },
      { nl: "de wijn", en: "the wine" },
      { nl: "proost", en: "cheers" },
      { nl: "eerst", en: "first" },

      // Cooking
      { nl: "het mes", en: "the knife" },
      { nl: "snijden", en: "to cut" },
      { nl: "de plak", en: "the slice" },
      { nl: "de oven", en: "the oven" },
      { nl: "de pan", en: "the pan" },
      { nl: "zetten", en: "to put" },
      { nl: "het vuur", en: "the fire" },
      { nl: "wachten", en: "to wait" },
      { nl: "ondertussen", en: "meanwhile" },
      { nl: "Italië", en: "Italy" },
      { nl: "altijd", en: "always" },
      { nl: "voetbal kijken", en: "to watch football" },
      { nl: "tegen", en: "against" },
      { nl: "gaar", en: "done (cooked)" },
      { nl: "halen", en: "to pick up" },
      { nl: "pakken", en: "to grab" },
      { nl: "de koekenpan", en: "the frying pan" },
      { nl: "het stuk", en: "the piece" },

      // Food & drink
      { nl: "de biet", en: "the beetroot" },
      { nl: "de soep", en: "the soup" },
      { nl: "de zure room", en: "the sour cream" },
      { nl: "misschien", en: "maybe" },
      { nl: "zoeken", en: "to search" },
      { nl: "pas", en: "1. just, only 2. really" },
      { nl: "schrikken", en: "to scare" },
      { nl: "de augurk", en: "the pickle" },
      { nl: "de grapefruit", en: "the grapefruit" },
      { nl: "de witlof", en: "the chicory" },
      { nl: "de croissant", en: "the croissant" },
      { nl: "de honing", en: "the honey" },
      { nl: "de chips", en: "the chips" },
      { nl: "de haring", en: "the herring" },
      { nl: "de nootjes", en: "the nuts" },
    ],
  },

  {
    id: 5,
    title: "Lesson 5 — Hoofdstuk 5: Het huis",
    words: [
      // Family & possessions
      { nl: "je, jouw", en: "your (singular, informal)" },
      { nl: "de broer", en: "the brother" },
      { nl: "uw", en: "your (singular, polite)" },
      { nl: "de sleutel", en: "the key" },
      { nl: "haar", en: "her" },
      { nl: "ziek", en: "ill" },
      { nl: "ons, onze", en: "our" },
      { nl: "het kleinkind", en: "the grandchild" },
      { nl: "de cd", en: "the cd" },
      { nl: "hun", en: "their" },
      { nl: "de ouder", en: "the parent" },
      { nl: "aardig", en: "nice, friendly" },
      { nl: "slim", en: "clever" },
      { nl: "blauw", en: "blue" },
      { nl: "de trui", en: "the sweater" },
      { nl: "het bed", en: "the bed" },
      { nl: "zwart", en: "black" },
      { nl: "kwijt (zijn)", en: "(to have) lost" },
      { nl: "rood", en: "red" },
      { nl: "deze", en: "this" },
      { nl: "die", en: "that" },
      { nl: "erg", en: "very" },
      { nl: "duur", en: "expensive" },
      { nl: "bestellen", en: "to order" },

      // Celebrating & everyday life
      { nl: "tijdens", en: "during" },
      { nl: "vieren", en: "to celebrate" },
      { nl: "de verjaardag", en: "the birthday" },
      { nl: "het licht", en: "the light" },
      { nl: "de muziek", en: "the music" },
      { nl: "de ballon", en: "the balloon" },
      { nl: "na", en: "after" },
      { nl: "de nacht", en: "the night" },
      { nl: "volgens", en: "according to" },
      { nl: "de gast", en: "the guest" },
      { nl: "naar huis gaan", en: "to go home" },
      { nl: "behalve", en: "except for" },
      { nl: "zonder", en: "without" },
      { nl: "de pagina", en: "the page" },
      { nl: "de doos", en: "the box, the case" },
      { nl: "het hoofdkantoor", en: "the head office" },
      { nl: "laten", en: "to let" },
      { nl: "laten zien", en: "to show" },

      // The living room & kitchen
      { nl: "de stoel", en: "the chair" },
      { nl: "de bank", en: "1. the couch 2. the bank" },
      { nl: "het telefoonnummer", en: "the phone number" },
      { nl: "de trofee", en: "the trophy" },
      { nl: "het uitzicht", en: "the view" },
      { nl: "Kom verder.", en: "Come in." },
      { nl: "de keuken", en: "1. the kitchen 2. the cuisine" },
      { nl: "het fornuis", en: "the stove" },
      { nl: "het aanrecht", en: "the kitchen counter" },
      { nl: "de magnetron", en: "the microwave oven" },
      { nl: "de bijkeuken", en: "the scullery" },
      { nl: "helaas", en: "unfortunately" },
      { nl: "de wasmachine", en: "the washing machine" },
      { nl: "kapot", en: "broken" },
      { nl: "de was", en: "the laundry" },
      { nl: "brengen", en: "to bring" },
      { nl: "de kleding", en: "the clothing" },
      { nl: "Dat meen je niet!", en: "You are kidding me!" },
      { nl: "menen", en: "to mean" },
      { nl: "wel", en: "opposite of not" },

      // Around the house
      { nl: "terug", en: "back" },
      { nl: "de gang", en: "the hallway" },
      { nl: "de wc", en: "the toilet" },
      { nl: "de badkamer", en: "the bathroom" },
      { nl: "de slaapkamer", en: "the bedroom" },
      { nl: "het tweepersoonsbed", en: "the double bed" },
      { nl: "alleen", en: "1. alone 2. only" },
      { nl: "Je weet maar nooit!", en: "You never know!" },
      { nl: "nooit", en: "never" },
      { nl: "de bel", en: "the bell" },

      // At the bar
      { nl: "aan de bar", en: "at the bar" },
      { nl: "de tap", en: "the beer tap" },
      { nl: "de ober", en: "the waiter" },
      { nl: "de wedstrijd", en: "the game" },
      { nl: "verliezen", en: "to lose" },
      { nl: "verdrietig", en: "sad" },
      { nl: "daarom", en: "that's why" },
      { nl: "vol", en: "full" },
    ],
  },
];
