// Dutch flashcard data.
//
// HOW TO ADD A NEW LESSON:
// Just copy the block below (from "{" to "},") and paste it as a new
// entry in the LESSONS array. Give it the next id/title, then fill in
// "words" as { nl: "...", en: "..." } pairs. That's it — the app picks
// up new lessons automatically, no other code changes needed.

const LESSONS = [
  {
    id: 1,
    title: "Lesson 1 — Introductie & De kennismaking",
    words: [
      // People & everyday things
      { nl: "de, het", en: "the" },
      { nl: "een", en: "a" },
      { nl: "de man", en: "the man" },
      { nl: "de vrouw", en: "the woman" },
      { nl: "de baby", en: "the baby" },
      { nl: "de hond", en: "the dog" },
      { nl: "de kat", en: "the cat" },
      { nl: "het dier", en: "the animal" },
      { nl: "de student", en: "the student" },
      { nl: "de docent", en: "the teacher" },
      { nl: "de les", en: "the lesson" },
      { nl: "de pen", en: "the pen" },
      { nl: "de tekst", en: "the text" },
      { nl: "het theater", en: "the theatre" },
      { nl: "het meisje", en: "the girl" },
      { nl: "het kind", en: "the child" },
      { nl: "het konijn", en: "the rabbit" },
      { nl: "het boek", en: "the book" },
      { nl: "het land", en: "the country" },
      { nl: "het adres", en: "the address" },
      { nl: "het antwoord", en: "the answer" },
      { nl: "het huis", en: "the house" },
      { nl: "de tablet", en: "the tablet" },
      { nl: "de smartphone", en: "the smartphone" },
      { nl: "het tennis", en: "the tennis" },
      { nl: "Veel succes!", en: "Good luck!" },

      // Names, cities, countries & languages
      { nl: "de naam", en: "the name" },
      { nl: "de voornaam", en: "the first name" },
      { nl: "de achternaam", en: "the surname" },
      { nl: "de stad", en: "the city" },
      { nl: "de taal", en: "the language" },
      { nl: "Nederland", en: "the Netherlands" },
      { nl: "het Nederlands", en: "the Dutch language" },
      { nl: "Duitsland", en: "Germany" },
      { nl: "het Duits", en: "the German language" },
      { nl: "Amerika", en: "America" },
      { nl: "het Engels", en: "the English language" },
      { nl: "China", en: "China" },
      { nl: "het Chinees", en: "the Chinese language" },
      { nl: "Rusland", en: "Russia" },
      { nl: "het Russisch", en: "the Russian language" },
      { nl: "Frankrijk", en: "France" },
      { nl: "het Frans", en: "the French language" },
      { nl: "Spanje", en: "Spain" },
      { nl: "Spaans", en: "Spanish" },

      // Pronouns
      { nl: "ik", en: "I" },
      { nl: "jij / je", en: "you (informal)" },
      { nl: "u", en: "you (polite)" },
      { nl: "hij", en: "he" },
      { nl: "zij / ze", en: "she" },
      { nl: "wij / we", en: "we" },
      { nl: "jullie", en: "you (plural)" },

      // Time: days, months, seasons
      { nl: "de dag", en: "the day" },
      { nl: "de week", en: "the week" },
      { nl: "de maand", en: "the month" },
      { nl: "het jaar", en: "the year" },
      { nl: "maandag", en: "Monday" },
      { nl: "dinsdag", en: "Tuesday" },
      { nl: "woensdag", en: "Wednesday" },
      { nl: "donderdag", en: "Thursday" },
      { nl: "vrijdag", en: "Friday" },
      { nl: "zaterdag", en: "Saturday" },
      { nl: "zondag", en: "Sunday" },
      { nl: "januari", en: "January" },
      { nl: "februari", en: "February" },
      { nl: "maart", en: "March" },
      { nl: "april", en: "April" },
      { nl: "mei", en: "May" },
      { nl: "juni", en: "June" },
      { nl: "juli", en: "July" },
      { nl: "augustus", en: "August" },
      { nl: "september", en: "September" },
      { nl: "oktober", en: "October" },
      { nl: "november", en: "November" },
      { nl: "december", en: "December" },
      { nl: "het seizoen", en: "the season" },
      { nl: "de lente", en: "the spring" },
      { nl: "de zomer", en: "the summer" },
      { nl: "de herfst", en: "the autumn" },
      { nl: "de winter", en: "the winter" },

      // Verbs
      { nl: "het werkwoord", en: "the verb" },
      { nl: "kijken", en: "to watch" },
      { nl: "de televisie", en: "the television" },
      { nl: "werken", en: "to work" },
      { nl: "op", en: "at / on" },
      { nl: "de universiteit", en: "the university" },
      { nl: "antwoorden", en: "to answer" },
      { nl: "de vraag", en: "the question" },
      { nl: "lopen", en: "to walk" },
      { nl: "leren", en: "to learn" },
      { nl: "vertellen", en: "to tell" },
      { nl: "wonen", en: "to live" },
      { nl: "in", en: "in" },
      { nl: "spreken", en: "to speak" },
      { nl: "al", en: "already" },
      { nl: "lezen", en: "to read" },
      { nl: "de krant", en: "the newspaper" },
      { nl: "geven", en: "to give" },
      { nl: "zitten", en: "to sit" },
      { nl: "buiten", en: "outside" },
      { nl: "hebben", en: "to have" },
      { nl: "zijn", en: "to be" },
      { nl: "sinds", en: "since" },
      { nl: "vanavond", en: "tonight" },
      { nl: "komen", en: "to come" },
      { nl: "uit", en: "from / out of" },
      { nl: "binnen", en: "inside" },
      { nl: "nu", en: "now" },
      { nl: "op dit moment", en: "at this moment" },

      // Greetings & meeting someone
      { nl: "ontmoeten", en: "to meet" },
      { nl: "hoi", en: "hi" },
      { nl: "wie", en: "who" },
      { nl: "aangenaam", en: "nice to meet you" },
      { nl: "Hoe heet jij?", en: "What is your name?" },
      { nl: "Ik heet...", en: "My name is..." },
      { nl: "en", en: "and" },
      { nl: "waar", en: "where" },
      { nl: "waar vandaan", en: "where from" },
      { nl: "een beetje", en: "a bit" },
      { nl: "wauw", en: "wow" },
      { nl: "veel", en: "much / many" },

      // Small talk phrases
      { nl: "welke", en: "which" },
      { nl: "Wat leuk!", en: "How nice!" },
      { nl: "ook", en: "too" },
      { nl: "doen", en: "to do" },
      { nl: "dat", en: "that" },
      { nl: "begrijpen", en: "to understand" },
      { nl: "mijn", en: "my" },
      { nl: "het beroep", en: "the profession" },
      { nl: "ja", en: "yes" },
      { nl: "de actrice", en: "the actress" },
      { nl: "Wat interessant!", en: "How interesting!" },
      { nl: "beginnen", en: "to begin" },
      { nl: "met", en: "with" },
      { nl: "dankjewel", en: "thank you" },
      { nl: "de koffie", en: "the coffee" },
      { nl: "alsjeblieft", en: "here you are / please" },
      { nl: "goed", en: "right / good" },
      { nl: "fout", en: "wrong / false" },

      // A story: guided tour
      { nl: "het verhaal", en: "the story" },
      { nl: "de rondleiding", en: "the guided tour" },
      { nl: "het werk", en: "the job" },
      { nl: "vandaag", en: "today" },
      { nl: "van", en: "from" },
      { nl: "het station", en: "the station" },
      { nl: "naar", en: "to" },
      { nl: "zeggen", en: "to say" },
      { nl: "dit", en: "this" },
      { nl: "het paleis", en: "the palace" },
      { nl: "vragen", en: "to ask" },
      { nl: "de koning", en: "the king" },
      { nl: "nee", en: "no" },
      { nl: "bij", en: "at" },
      { nl: "de vrijgezel", en: "the bachelor" },
      { nl: "maar", en: "but / only" },
      { nl: "geen", en: "no / none" },
      { nl: "verder", en: "further" },
      { nl: "leuk", en: "fun" },
      { nl: "over", en: "about" },
    ],
  },

  {
    id: 2,
    title: "Lesson 2 — Hoofdstuk 2: Vragen",
    words: [
      // Money & time
      { nl: "laat", en: "late" },
      { nl: "hoeveel", en: "how many / how much" },
      { nl: "het geld", en: "the money" },

      // Degree words & adjectives
      { nl: "spelen", en: "to play" },
      { nl: "heel", en: "1. very 2. whole" },
      { nl: "zeer", en: "very" },
      { nl: "klein", en: "small" },
      { nl: "nogal", en: "quite" },
      { nl: "boos", en: "angry" },
      { nl: "redelijk", en: "rather" },
      { nl: "knap", en: "handsome" },
      { nl: "hartstikke", en: "extremely" },
      { nl: "mooi", en: "beautiful" },
      { nl: "gisteren", en: "yesterday" },
      { nl: "morgen", en: "tomorrow" },
      { nl: "nieuw", en: "new" },
      { nl: "het woord", en: "the word" },
      { nl: "de film", en: "the movie" },

      // Time, place & grammar
      { nl: "zo", en: "soon" },
      { nl: "straks", en: "in a little while" },
      { nl: "binnenkort", en: "soon" },
      { nl: "Sinterklaas", en: "Dutch Santa Claus" },
      { nl: "daar", en: "there" },
      { nl: "hier", en: "here" },
      { nl: "liggen", en: "to lie (be located)" },
      { nl: "inversie", en: "inversion (grammar)" },
      { nl: "de tuin", en: "the garden" },
      { nl: "de kapper", en: "the hairdresser" },
      { nl: "drinken", en: "to drink" },
      { nl: "de stamppot", en: "the hotchpotch" },
      { nl: "moeten", en: "to have to, must" },
      { nl: "klaar", en: "ready" },
      { nl: "het vraagwoord", en: "the question word" },

      // Market, questions & everyday life
      { nl: "de markt", en: "the market" },
      { nl: "de kinderen", en: "the children" },
      { nl: "het bezoek", en: "1. visit 2. guests" },
      { nl: "vaak", en: "often" },
      { nl: "fietsen", en: "to cycle" },
      { nl: "lesgeven", en: "to teach" },
      { nl: "wat", en: "what" },
      { nl: "je adres", en: "your address" },
      { nl: "aan", en: "to" },
      { nl: "welk, welke", en: "which" },
      { nl: "gebruiken", en: "to use" },
      { nl: "wanneer", en: "when" },
      { nl: "de jongen", en: "the boy" },
      { nl: "de oefening", en: "the exercise" },
      { nl: "jarig zijn", en: "to have a birthday" },
      { nl: "plat", en: "flat" },
      { nl: "hoe heten", en: "how ... called (e.g. Hoe heet jij? = What are you called?)" },

      // A phone call
      { nl: "bellen", en: "to call" },
      { nl: "hallo", en: "hello" },
      { nl: "Hoe gaat het met jou?", en: "How are you?" },
      { nl: "jou", en: "you" },
      { nl: "de roman", en: "the novel" },
      { nl: "waarom", en: "why" },
      { nl: "gewoon", en: "normal / just" },
      { nl: "weten", en: "to know" },
      { nl: "nog", en: "still / yet" },
      { nl: "niet", en: "not" },
      { nl: "eten", en: "to eat" },
      { nl: "het idee", en: "the idea" },
      { nl: "mij", en: "me" },
      { nl: "Goed idee!", en: "Good idea!" },
      { nl: "koken", en: "to cook" },
      { nl: "thuis", en: "at home" },
      { nl: "willen", en: "to want" },
      { nl: "Weet je wat?", en: "You know what?" },
      { nl: "samen", en: "together" },
      { nl: "daarna", en: "then / after that" },
      { nl: "tot", en: "until" },
      { nl: "nemen", en: "to take" },
      { nl: "de trein", en: "the train" },
      { nl: "meteen", en: "immediately" },
      { nl: "prima", en: "fine" },
      { nl: "de buurt", en: "the neighbourhood" },
      { nl: "de kilometer", en: "the kilometre" },
      { nl: "het Centraal Station", en: "the Central Station" },
      { nl: "ongeveer", en: "approximately" },
      { nl: "dan", en: "then" },
      { nl: "zien", en: "to see" },
      { nl: "Tot straks!", en: "See you later!" },
      { nl: "doei", en: "bye" },

      // Wrapping up
      { nl: "door", en: "through" },
      { nl: "kennen", en: "to know" },
      { nl: "zuchten", en: "to sigh" },
      { nl: "kunnen", en: "1. to be able to 2. to be available" },
      { nl: "druk", en: "1. busy 2. crowded" },
      { nl: "de eeuw", en: "the century" },
      { nl: "het einde", en: "the end" },
    ],
  },

  // Lesson 3 goes here — send more photos any time and it'll be added
  // the same way.
];
